export const imagenes = {
    bocatalogo: require('/bocata-logo.png'),
    descuento: require('./descuento.png'),
    draw1: require('./draw-1.svg'),
    draw2: require('./draw-2.svg'),
    draw3: require('./draw-3.svg'),
    draw4: require('./draw-4.svg'),
    draw5: require('./draw-5.svg'),
    draw6: require('./draw-6.svg'),
    draw7: require('./draw-7.svg'),
    draw8: require('./draw-8.svg'),
    fbicon: require('./fb-icon.png'),
    flechaimg: require('./flecha-img.png'),
    ganadoricon: require('./ganador-icon.png'),
    ganadorsorteo: require('./ganador-sorteo-1.png'),
    horario: require('./horario.png'),
    iconig: require('./icon-ig.svg'),
    marcoimg: require('./marco-img-ganadores.png'),
    telicon: require('./tel-icon.png'),
    tiktokicon: require('./tiktok-icon.png'),
    ubicacion: require('./ubicacion.png'),
  };
  